language: node_js
sudo: false
node_js:
  - 12

install:
  - npm install

script:
  - npm run build

deploy:
  provider: releases
  prerelease: true
  api_key: ${GH_TOKEN}
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    tags: true
    branch: master